// src/components/Footer.vue
<template>
    <footer>
        <p><a href="https://github.com/mttaggart/wtfbins">Made</a> with 💙 by <a href="https://taggart-tech.com">Taggart Tech</a></p>
    </footer>
</template>

<style scoped>
    footer p, footer a {
        font-size: 1.5rem;
        text-align: center;
        font-family: "SportsNight";
        color: white;
    }
</style>

// components/footer.tsx
import styles from "../styles/Footer.module.css"

export default function Footer() {
    return (
        <footer className={styles.footer}>
            <p>
                <a href="https://github.com/mttaggart/wtfbins">Made</a> with 💜 by <a href="https://taggartinstitute.com">The Taggart Institute</a>
            </p>
        </footer>
    );
}
